color: null
fieldLayouts:
  feb043f3-4eaa-46e1-9489-7d769708ea3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-13T07:49:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 675f4f32-f98e-4076-a632-c6f29c5e898d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T07:57:48+00:00'
            elementCondition: null
            fieldUid: 4bc8eaf1-77be-48c6-86ba-36a1d17893cc # Gallery List Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fca6f1af-35cf-48e0-a27b-276123fc1f89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T07:55:11+00:00'
            elementCondition: null
            fieldUid: 4dcb8646-ad96-499f-b7c8-1e6d186f86a1 # Gallery Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5b48a17-06ef-462f-98e9-27ed458ccb2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T07:55:11+00:00'
            elementCondition: null
            fieldUid: 2ccde052-6c59-4d1b-bf8d-70cb301d4753 # Gallery Grid Class
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aafe279a-94db-46f7-b240-da86c9541aaf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T07:55:11+00:00'
            elementCondition: null
            fieldUid: 39b97c64-fd3e-498d-bcf1-3838a8c4ac4e # Gallery Post
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b117703-93ff-466d-bbed-8ef9a302320b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1a859c7-d878-4e32-bb77-c5b283651e5d
        userCondition: null
handle: galleryList
hasTitleField: true
icon: null
name: 'Gallery List'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
