color: null
fieldLayouts:
  901baed7-a510-4f6f-a6e1-79315f80513c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-10T09:02:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 700420a3-c51f-411b-ba65-73a733989bce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T09:17:46+00:00'
            elementCondition: null
            fieldUid: 3ed901e0-32d6-46cc-bb5c-8b5d81add716 # Banner Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8dec0f4-04ff-4e4f-98ce-c58f779ae495
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-10T09:17:46+00:00'
            elementCondition: null
            fieldUid: 7c29c120-eff3-46bd-91f1-2235e68cdaa4 # Banner Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0ccc1de-5103-4dbf-b9dc-5d0da7f2e4a4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 92dc51ae-ceb0-4583-a9dd-b78426acdc1d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-13T06:10:35+00:00'
            elementCondition: null
            fieldUid: 51768e46-ef5c-46e2-bd19-81ddc6ec2135 # About Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b360be92-5c4f-4760-b11a-abafbe2a0104
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T06:10:35+00:00'
            elementCondition: null
            fieldUid: e6e1d203-8dd6-43e6-ae50-17188cda1a25 # About Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75ea3422-1ebd-434f-968f-a252fd09f24a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T05:46:55+00:00'
            elementCondition: null
            fieldUid: 2f36ea61-ec39-49c9-8774-ca1927e13859 # About Photography Skills
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d94e4db2-4159-4af5-ac27-0c4162499cc4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T06:15:35+00:00'
            elementCondition: null
            fieldUid: 59b7b560-eea6-4372-ba41-42299230a3b5 # About Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e3d0e6-1310-4bd3-821c-b1ec07178777
            userCondition: null
            warning: null
            width: 100
        name: About
        uid: 20e5acb9-1d8e-43bd-b545-fb4eb2f8d4e7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-13T07:06:15+00:00'
            elementCondition: null
            fieldUid: b2ceae8b-1f73-4745-a97c-d16e13b0c99b # Gallery Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fda1d02c-8f9b-4ee5-896f-7384cd773eb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T07:58:18+00:00'
            elementCondition: null
            fieldUid: 5394c62f-6b64-47af-a5c6-2a4197bb68c6 # Gallery List
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c1fa53f-4e24-467c-8f9c-a6089e6e1f45
            userCondition: null
            warning: null
            width: 100
        name: Gallery
        uid: a6f1462d-0bc5-4ede-b50c-8beeb795e791
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-13T14:34:06+00:00'
            elementCondition: null
            fieldUid: 096db8d6-0fe7-402b-b5c2-0e640aa3a64f # Services Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9237435-2b55-4a58-ac76-bae98bb5a7f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T14:34:06+00:00'
            elementCondition: null
            fieldUid: 30cf4ce7-0d33-4bdd-8260-d5fd917dc606 # Services Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8001e756-7995-4d76-a6ce-1f214a0dae91
            userCondition: null
            warning: null
            width: 100
        name: Services
        uid: c1822e0c-2697-46e2-91c4-64dd6072fc04
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-13T14:51:44+00:00'
            elementCondition: null
            fieldUid: 206df58c-4891-442a-9362-b37625e24001 # Review Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81e1282e-d622-4439-a95c-c1c867e469fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T14:51:44+00:00'
            elementCondition: null
            fieldUid: a6ba4441-bf9d-46c5-aaaa-0c475468cfda # Review Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57f7b859-0d3d-4d87-adc9-01f656eb2e5e
            userCondition: null
            warning: null
            width: 100
        name: Review
        uid: fc01acaf-72ff-4daa-9214-d73d816fade4
        userCondition: null
handle: home
hasTitleField: true
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
