color: null
fieldLayouts:
  0c112486-6baa-4964-ab48-107fd5bd29dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-13T14:29:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c398b418-f920-4762-9f03-a39fbf89c566
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T14:33:46+00:00'
            elementCondition: null
            fieldUid: 254c9984-3e10-41c2-98c4-3fff8309bd0b # Services Class Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64287d21-8c53-45c8-a4b6-16301a5575a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-13T14:33:46+00:00'
            elementCondition: null
            fieldUid: 87f73687-cdcc-4842-a252-f6cbcff6e137 # Services Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14144dd4-ae97-4b73-af04-bfba89f96862
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 45028087-f71c-4278-a7e5-74282090eeb7
        userCondition: null
handle: servicesContent
hasTitleField: true
icon: null
name: 'Services Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
