headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Custom
options:
  alignment:
    options:
      - left
      - right
  format_bold:
    element: b
    overrides: strong
  style:
    definitions:
      -
        classes:
          - red-heading
        element: h2
        name: 'Red heading'
      -
        classes:
          - vibrant-code
        element: pre
        name: 'Vibrant code'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - style
  - alignment
  - underline
  - strikethrough
  - code
  - insertImage
  - insertTable
  - blockQuote
  - htmlEmbed
  - link
  - sourceEditing
