altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fa6f4fad-d0e5-4c18-9819-78accf4bc046:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-10T08:51:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 189ee210-caff-4ba7-bbed-acc5031c8ad7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d090dad6-92bb-4c30-b700-9b5bb6f88cc9
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
