columnSuffix: null
handle: galleryListTitle
instructions: null
name: 'Gallery List Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Enter a title'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
