defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fd9098f3-042e-4c54-8127-bed6483c9100 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3fcde770-5269-4298-8782-54dd7c435a9c: # my-craft-cleanphotography
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
